#本地配置
server:
  port: 18888

##########   数据库   ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoxise
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 0
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379
      # 连接密码（默认为空）
      password:

##########   框架配置   ##########

####################   mybatis   ####################
mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 全局主键策略
  type-handlers-package: cn.hoxise.common.base.framework

#################### Sa-Token 配置 (文档: https://sa-token.cc) ####################
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: hoxise-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


##########   其它配置   ##########
project:
  #启动模式 (dev 1.登录不需要验证码;2.禁用SSL证书验证)
  runMode: dev
  #项目启动后是否清除Redis
  isClearCache: false
  #redis默认过期时间 Hour
  redisTimeout: 12

#文件存储
fileStorage:
  defaultType: minio
  minio:
    endpoint: http://127.0.0.1:9000
    bucket: hoxise-java
    access-key: hoxise
    secret-key: hoxise-java

#短信
sms:
  aliyun:
    accessKey: ${aliyun.ram.accessKey}
    accessSecret: ${aliyun.ram.accessSecret}

#nas云处理
nasCloud:
  #需要管理的盘符及前缀
  disk: X:\
  #需要管理的文件夹
  dirs: 动漫电影,动漫,日剧