#本地配置


##########   数据库   ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoxise
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 0
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379
      # 用户名
      username:
      # 连接密码（默认为空）
      password:

  # openai
  ai:
    openai:
      # API密钥
      api-key: ${deepseek.api.key}
      # DeepSeek的API端点
      base-url: https://api.deepseek.com
      chat:
        options:
          # 可选模型：deepseek-chat(非思考模式), deepseek-reasoner (思考模式)
          model: deepseek-chat
          # 回答随机性 默认1
          temperature: 1
          # 最大返回token
          max-tokens: 2000
    # 聊天记忆持久化
    chat:
      memory:
        repository:
          jdbc:
            # 可选值 embedded(默认,只有嵌入式数据库才建表) 、always(自动建表)、 never
            initialize-schema: always
    # 向量数据库
    vectorstore:
      # 向量模型
      embeddingModel:
        api-key: ${aliyun.bailian.ai.api.key}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        model: text-embedding-v4
      # 需要redis-stack
      redis:
        # 是否初始化所需表 默认false
        initialize-schema: false
        index-name: spring-ai-index
        prefix: "embedding:"


## Sa-Token 配置 (文档: https://sa-token.cc) ##
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天(2592000)，-1 代表永久有效
  timeout: 259200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


##########   其它配置   ##########
project:
  #启动模式 (dev 1.登录不需要验证码;)
  runMode: dev
  #项目启动后是否清除Redis
  isClearCache: false
  #redis默认过期时间 Hour
  redisTimeout: 24

#文件存储
fileStorage:
  defaultType: aliyunOss
  #序列化前缀 如: 配置策略后直接访问的地址; CDN加速服务器
  serializerPrefix: ${aliyun.oss.serializerPrefix} # http://localhost:9000
  minio:
    endpoint: http://127.0.0.1:9000
    bucket: hoxise-java
    access-key: hoxise
    access-secret: hoxise-java
  aliyunOss:
    regin: cn-chengdu
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucket: ${aliyun.oss.bucket}
    access-key: ${aliyun.oss.accessKey}
    access-secret: ${aliyun.oss.accessSecret}


#短信
sms:
  aliyun:
    endpoint: dypnsapi.aliyuncs.com
    accessKey: ${aliyun.sms.accessKey}
    accessSecret: ${aliyun.sms.accessSecret}

#nas云处理
nasCloud:
  #需要管理的盘符及前缀
  disk: X:\
  #需要管理的文件夹
  dirs: 动漫电影,动漫,日剧
  #启动后是否加载Embedding
  pushVectorStore: false
